name: Regression Tests (NodeJS)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      upstream-version:
        description: Upstream aws-cdk version to use in tests
        required: false
env:
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test

jobs:
  integration-nodejs:
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      localstack:
        image: localstack/localstack:latest
        env:
          SERVICES: cloudformation,iam,sts,ssm,s3,cloudwatch,cloudwatch-logs,lambda,sns,dynamodb,apigateway
          DEFAULT_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: localkey
          AWS_SECRET_ACCESS_KEY: localsecret
        ports:
          - 4566:4566
          - 4571:4571

    strategy:
      matrix:
        include:
          - { language: javascript, node-version: '20.x', region: us-east-1}
          

    env:
      AWS_REGION: ${{ matrix.region }}
      AWS_DEFAULT_REGION: ${{ matrix.region }}

    steps:
      - uses: actions/checkout@v2
       
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      

      - name: Install specific aws-cdk version
        
        
        run: npm install -g aws-cdk-local aws-cdk

      
      - name: Run bootstrap
        timeout-minutes: 1
        run: |
            curl -v http://localhost:4566
            npm install
            cdklocal bootstrap

      - name: Deploy
        timeout-minutes: 1
        run: cdklocal deploy --all --require-approval=never

      - name: Verify successful deployment
        run: |
         aws --endpoint-url=http://localhost:4566  s3 ls
         echo "Test Execution complete!"    
